### ISSUE TITLE
dezoomify-node.js fails to encode urls

### ISSUE THREAD

**Issue by madalu** [lovasoa/dezoomify#128]
node-dezoomify.js fails to encode url, thus resulting in the following error

```% node dezoomify-node.js "http://www.theeuropeanlibrary.org/tel4/ecloud?iiif=/data-providers/TheEuropeanLibrary/records/3000096325245/representations/presentation_images/node-2/image/SBB/Berliner_Börsenzeitung/1872/07/19/F_000_332_0/F_SBB_00007_18720719_000_332_0_001/info.json" out.jpg

0% : Found image. Trying to open it...
1% : Sent a request in order to get informations about the image...
0% : The dezoomer is trying to locate the zoomable image...
0% : Launched dezoomer...
Requested: http://www.theeuropeanlibrary.org/tel4/ecloud?iiif=/data-providers/TheEuropeanLibrary/records/3000096325245/representations/presentation_images/node-2/image/SBB/Berliner_B%C3%B6rsenzeitung/1872/07/19/F_000_332_0/F_SBB_00007_18720719_000_332_0_001/info.json
0% : Preparing tiles load...
file:///home/matt/dezoomify/zoommanager.js:62
        UI.ctx.drawImage(tileImg, x, y);
               ^

Error: Image given has not completed loading
    at Object.UI.drawTile (file:///home/matt/dezoomify/zoommanager.js:62:9)
    at Request.tileLoaded [as _callback] (/home/matt/dezoomify/node-app/dezoomify-node.js:51:10)
    at Request.self.callback (/home/matt/dezoomify/node-app/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (/home/matt/dezoomify/node-app/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at IncomingMessage.<anonymous> (/home/matt/dezoomify/node-app/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:293:19)
```
The initial url is encoded properly, but the tiles url received from the info.json file is not. I.e., line 40 of dezoomify-node.js requests unencoded urls that look like this:

`http://iiif.europeana.eu//data-providers/TheEuropeanLibrary/records/3000096325245/representations/presentation_images/node-2/image/SBB/Berliner_Börsenzeitung/1872/07/19/F_000_332_/F_SBB_00007_18720719_000_332_0_001/4864,7424,256,256/256,256/0/default.jpg`

**Comment by AlexanderDeLargeBrotherSir** [comment]
@madalu, can you check if the issue is resolved ?
And if it is, then i very humbly and politely ask you to close this at your earliest convenience.
