### ISSUE TITLE
can't download images with PHP server or node-app

### ISSUE THREAD

**Issue by michaelw3** [lovasoa/dezoomify#164]
hi i cant download images after installing the node-app or running a PHP server.

in the node-app i get the following error-

```
1% : Sent a request in order to get informations about the image...
Requested: {the url i sent}
0% : Preparing tiles load...
.../dezoomify-master/dezoomify-master/zoommanager.js:62
        UI.ctx.drawImage(tileImg, x, y);
               ^

Error: Image given has not completed loading
    at Error (native)
    at Object.UI.drawTile (file:///C:/Users/.../dezoomify-master/dezoomify-master/zoommanager.js:62:9)
    at Request.tileLoaded [as _callback] (C:\Users\...\dezoomify-master\dezoomify-master\node-app\dezoomify-node.js:51:10)
    at Request.self.callback (C:\Users\...\dezoomify-master\dezoomify-master\node-app\node_modules\request\request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (C:\Users\...\dezoomify-master\dezoomify-master\node-app\node_modules\request\request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (C:\Users\...\dezoomify-master\dezoomify-master\node-app\node_modules\request\request.js:1091:12)
```

when running as a PHP server i get the following error-
`Uncaught Error: Invalid JSON: http://.../info.json (http://localhost:8080/zoommanager.js:170)`

**Comment by michaelw3** [comment]
**UPDATE**

i got the PHP server to work, but somehow when i try to download from IIIF server i get the image downloaded multiple times in the same file - 
![2017-07-14](https://user-images.githubusercontent.com/8994886/28202252-28b14f94-687d-11e7-90d9-b15bb4164d64.png)
