### ISSUE TITLE
Error: socket hang up

### ISSUE THREAD

**Issue by adunning** [lovasoa/dezoomify#232]
I periodically receive a 'socket hang up' error when making an initial request with the Nod app. It seems to be pretty much random, and works again when retrying. Could Dezoomify try again if it runs into this instead of stopping?

This is the output (Node v10.1.0):

```
Requested: [URL]
Error: Error: socket hang up
    at dispatchError (/dezoomify/node-app/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:895:74)
    at Request.client.on.err (/dezoomify/node-app/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:612:11)
    at Request.emit (events.js:187:15)
    at Request.onRequestError (/dezoomify/node-app/node_modules/request/request.js:878:8)
    at ClientRequest.emit (events.js:182:13)
    at Socket.socketOnEnd (_http_client.js:409:9)
    at Socket.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1086:12)
    at process._tickCallback (internal/process/next_tick.js:63:19) undefined
```

**Comment by lovasoa** [comment]
I recently updated the node app, and it now uses the latest version of jsdom.
If you are still experiencing this problem, please comment here and we'll reopen the issue and investigate.
Please also note that we released [dezoomify-rs](https://github.com/lovasoa/dezoomify-rs), which should be faster, easier to use, and more featureful than the node app.
