### ISSUE TITLE
error when running zoomify-node.js

### ISSUE THREAD

**Issue by jeffstud** [lovasoa/dezoomify#276]
Hi,
When I run zoomify-node.js, I get a error message:

```
Error: Cannot find module 'jsdom/lib/old-api.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Program Files\nodejs\dezoomify-node.js:2:13)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```

I have installed node.js. I donot know how to use node-canvas.
Could you tell me how I can solve it?
Thank you very much.
Jeff

**Comment by jeffstud** [comment]
Hi, Lovasoa,
Could you offer a step by step tutorial for the usage of zoomify-node.js?
The OS of my computer is Windows.
Thank you very much!
Jeff

**Comment by lovasoa** [comment]
Hello,
  I'm answering very late, but I just wanted to comment just in case someone would stumble on that thread. For anyone wanting to use dezoomify from the commandline, I would recommend [**dezoomify-rs**](https://github.com/lovasoa/dezoomify-rs). It's a zoomable image downloader just like the dezoomify website, it also supports multiple image formats, but it was designed from the ground up as a commandline application: it's faster, lighter, has more features and is easier to install than dezoomify on node.js.

**Comment by lovasoa** [comment]
Ok, for the sake of fixing bugs, I still went back to the code of the node application and fixed it.
