### ISSUE TITLE
New site support: https://ngmdb.usgs.gov

### ISSUE THREAD

**Issue by furatxp3** [lovasoa/dezoomify#289]
Hello guys,

I have tried several ways to this link and always failed to use dezoomify, Is anyone can help me with this:

Here is the link that I want to donwloed map from :
https://ngmdb.usgs.gov/ngm-bin/pdp/zui_viewer.pl?id=14540

If I use http://ophir.alwaysdata.net/dezoomify/ and chose Zoomify It will load the image but won't let me save it both chrome and firefox.

Here is the link i'm using 
https://ngmdb.usgs.gov/img2/71000_71999/71889_1

If I want to download it through dezoomify-node.js it's giving me this error:

C:\dezoomify-master\dezoomify-master\node-app>node dezoomify-node.js "https://ngmdb.usgs.gov/img2/71000_71999/71889_1" "2.jpg"
1% : Sent a request in order to get information about the image...
0% : Launched dezoomer...
Requested: https://ngmdb.usgs.gov/img2/71000_71999/71889_1
Unable to find a proper dezoomer for:
https://ngmdb.usgs.gov/img2/71000_71999/71889_1

(file:///C:/dezoomify-master/dezoomify-master/dezoomers/automatic.js:30)
Error: Uncaught [Error: Unable to find a proper dezoomer for:
https://ngmdb.usgs.gov/img2/71000_71999/71889_1]
    at reportException (C:\dezoomify-master\dezoomify-master\node-app\node_modules\jsdom\lib\jsdom\living\helpers\runtime-script-errors.js:66:24)
    at invokeEventListeners (C:\dezoomify-master\dezoomify-master\node-app\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:209:9)
    at XMLHttpRequestEventTargetImpl._dispatch (C:\dezoomify-master\dezoomify-master\node-app\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:119:9)
    at XMLHttpRequestEventTargetImpl.dispatchEvent (C:\dezoomify-master\dezoomify-master\node-app\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:82:17)
    at XMLHttpRequest.dispatchEvent (C:\dezoomify-master\dezoomify-master\node-app\node_modules\jsdom\lib\jsdom\living\generated\EventTarget.js:157:21)
    at Request.properties.client.on (C:\dezoomify-master\dezoomify-master\node-app\node_modules\jsdom\lib\jsdom\living\xmlhttprequest.js:941:11)
    at Request.emit (events.js:194:15)
    at IncomingMessage.<anonymous> (C:\dezoomify-master\dezoomify-master\node-app\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:277:13)
    at IncomingMessage.emit (events.js:194:15) Error: Unable to find a proper dezoomer for:
https://ngmdb.usgs.gov/img2/71000_71999/71889_1
    at processNextUrl (file:///C:/dezoomify-master/dezoomify-master/dezoomers/automatic.js:30:13)
    at file:///C:/dezoomify-master/dezoomify-master/dezoomers/automatic.js:53:7
    at XMLHttpRequest.xhr.onloadend (file:///C:/dezoomify-master/dezoomify-master/zoommanager.js:371:3)
    at XMLHttpRequest.el.addEventListener.event (C:\dezoomify-master\dezoomify-master\node-app\node_modules\jsdom\lib\jsdom\living\helpers\create-event-accessor.js:33:32)
    at invokeEventListeners (C:\dezoomify-master\dezoomify-master\node-app\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:193:27)
    at XMLHttpRequestEventTargetImpl._dispatch (C:\dezoomify-master\dezoomify-master\node-app\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:119:9)
    at XMLHttpRequestEventTargetImpl.dispatchEvent (C:\dezoomify-master\dezoomify-master\node-app\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:82:17)
    at XMLHttpRequest.dispatchEvent (C:\dezoomify-master\dezoomify-master\node-app\node_modules\jsdom\lib\jsdom\living\generated\EventTarget.js:157:21)
    at Request.properties.client.on (C:\dezoomify-master\dezoomify-master\node-app\node_modules\jsdom\lib\jsdom\living\xmlhttprequest.js:941:11)
    at Request.emit (events.js:194:15)

C:\dezoomify-master\dezoomify-master\node-app>

**Comment by lovasoa** [comment]
Hello,
  This is a zoomify image. You can dezoom it by finding the `ImageProperties.xml` URL: 

https://ophir.alwaysdata.net/dezoomify/dezoomify.html#https://ngmdb.usgs.gov/img2/71000_71999/71889_1/ImageProperties.xml

![canvas](https://user-images.githubusercontent.com/552629/63364178-5bc8ff80-c375-11e9-91ec-eadefc403c82.jpg)


As for the node application, it hasn't been updated in a long time, and has several limitations, which made me start the [dezoomify-rs](https://github.com/lovasoa/dezoomify-rs) project, which works faster, is easier to install, and uses less memory.

**Comment by lovasoa** [comment]
I added support for the openseadragon zoomify plugin, that your site uses. You now enter the viewer URL directly into dezoomify:

https://ophir.alwaysdata.net/dezoomify/dezoomify.html#https://ngmdb.usgs.gov/ngm-bin/pdp/zui_viewer.pl?id=14540

This solves your initial issue.
