### ISSUE TITLE
error with node 12 on ubuntu 18

### ISSUE THREAD

**Issue by eligurevich** [lovasoa/dezoomify#306]
I am running dezoomify using node on Ubuntu on Win 10.

Today I upgraded to the latest dezoomify with node 12.7.0 and npm 6.10.0.

Now I get the following error on any link. But the tiles still download in the end, despite the error. 

Please let me know how to fix this.

gurevich@ELI-COMPUTER:~$ sh dezoomify-one-file.sh
Error: Uncaught [SyntaxError: Unexpected token export]
    at reportException (/home/gurevich/dezoomify/node-app/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:24)
    at processJavaScript (/home/gurevich/dezoomify/node-app/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:192:7)
    at HTMLScriptElementImpl._innerEval (/home/gurevich/dezoomify/node-app/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:122:5)
    at /home/gurevich/dezoomify/node-app/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:31:22
    at Object.check (/home/gurevich/dezoomify/node-app/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:76:11)
    at /home/gurevich/dezoomify/node-app/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:95:12
    at wrappedEnqueued (/home/gurevich/dezoomify/node-app/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:253:16)
    at ReadStream.<anonymous> (/home/gurevich/dezoomify/node-app/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:74:7)
    at ReadStream.emit (events.js:208:15)
    at endReadableNT (_stream_readable.js:1161:12) file:///home/gurevich/dezoomify/dezoomers/google-arts-culture-crypto.js:83
export {
^^^^^^

SyntaxError: Unexpected token export
    at new Script (vm.js:86:7)
    at createScript (vm.js:268:10)
    at Object.runInContext (vm.js:299:10)
    at processJavaScript (/home/gurevich/dezoomify/node-app/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:190:10)
    at HTMLScriptElementImpl._innerEval (/home/gurevich/dezoomify/node-app/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:122:5)
    at /home/gurevich/dezoomify/node-app/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:31:22
    at Object.check (/home/gurevich/dezoomify/node-app/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:76:11)
    at /home/gurevich/dezoomify/node-app/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:95:12
    at wrappedEnqueued (/home/gurevich/dezoomify/node-app/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:253:16)
    at ReadStream.<anonymous> (/home/gurevich/dezoomify/node-app/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:74:7)
Error: Uncaught [SyntaxError: Unexpected token {]
    at reportException (/home/gurevich/dezoomify/node-app/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:24)
    at processJavaScript (/home/gurevich/dezoomify/node-app/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:192:7)
    at HTMLScriptElementImpl._innerEval (/home/gurevich/dezoomify/node-app/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:122:5)
    at /home/gurevich/dezoomify/node-app/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:31:22
    at Object.check (/home/gurevich/dezoomify/node-app/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:76:11)
    at /home/gurevich/dezoomify/node-app/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:95:12
    at wrappedEnqueued (/home/gurevich/dezoomify/node-app/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:253:16)
    at ReadStream.<anonymous> (/home/gurevich/dezoomify/node-app/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:74:7)
    at ReadStream.emit (events.js:208:15)
    at endReadableNT (_stream_readable.js:1161:12) file:///home/gurevich/dezoomify/dezoomers/google-arts-culture.js:1
import { compute_signed_path, decrypt_image } from './google-arts-culture-crypto.js';
       ^

SyntaxError: Unexpected token {
    at new Script (vm.js:86:7)
    at createScript (vm.js:268:10)
    at Object.runInContext (vm.js:299:10)
    at processJavaScript (/home/gurevich/dezoomify/node-app/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:190:10)
    at HTMLScriptElementImpl._innerEval (/home/gurevich/dezoomify/node-app/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:122:5)
    at /home/gurevich/dezoomify/node-app/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:31:22
    at Object.check (/home/gurevich/dezoomify/node-app/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:76:11)
    at /home/gurevich/dezoomify/node-app/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:95:12
    at wrappedEnqueued (/home/gurevich/dezoomify/node-app/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:253:16)
    at ReadStream.<anonymous> (/home/gurevich/dezoomify/node-app/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:74:7)
1% : Sent a request in order to get information about the image...
0% : Launched dezoomer...
Requested: http://www.bl.uk/onlinegallery/onlineex/unvbrit/p/zoomify83328.html
1% : Sent a request in order to get information about the image...
0% : The dezoomer is trying to locate the zoomable image...
Requested: http://www.bl.uk/onlinegallery/onlineex/unvbrit/p/zoomify83328.html
0% : Found image. Trying to open it...
1% : Sent a request in order to get information about the image...
Requested: http://ogimages.bl.uk/images/zoomify/001/001HRL000007182U00060VRB/ImageProperties.xml
0% : Preparing tiles load...
1% : Loading the tiles...
30% : Loading the tiles...
75% : Loading the tiles...
100% : Loading the tiles...

**Comment by lovasoa** [comment]
Hello, and thank you for the bug report! I think this is due to the Google arts and culture dezoomer, that uses JavaScript modules. 
In the node application, dezoomify's web page is loaded inside jsdom, which doesn't seem to support js modules.

**Comment by lovasoa** [comment]
see: https://github.com/jsdom/jsdom/issues/2475

**Comment by lovasoa** [comment]
The easiest way to fix this might be to rewrite the google arts and culture dezoomer  in a way that does not use es modules.

**Comment by eligurevich** [comment]
Can you rewrite it?

**Comment by lovasoa** [comment]
I could, but it's not on my priority list. I'm currently working on [dezoomify-rs](https://github.com/lovasoa/dezoomify-rs), which I think will be a better alternative to the dezoomify node application, which is a little bit hacky.

**Comment by eligurevich** [comment]
Ok. Would dezoomify-rs run on ubuntu? When would it be ready?

**Comment by lovasoa** [comment]
Yes it will work on every platform. I don't have any ETA, this is a project I work on during my free time.

If you want to contribute, I'll be happy to guide you.

**Comment by eligurevich** [comment]
Thanks. But I am not a software expert.

**Comment by lovasoa** [comment]
Since today, [dezoomify-rs](https://github.com/lovasoa/dezoomify-rs) supports the dezoomify protocol. So you can use it for your usecase. Give it in input

```
http://ogimages.bl.uk/images/zoomify/001/001HRL000007182U00060VRB/ImageProperties.xml
```

**Comment by eligurevich** [comment]
Thanks. I will try.

**Comment by eligurevich** [comment]
I can't get the executable file inside the Linuz zip to run. I changed it
to executable using chmod, but it still does not run. Please send
instructions.

**Comment by lovasoa** [comment]
@eligurevich : I opened an issue on the bug tracker for dezoomify-rs (https://github.com/lovasoa/dezoomify-rs/issues/4)

**Comment by lovasoa** [comment]
The problem should be fixed now : 

https://asciinema.org/a/e7DbBXQh0kOEU9bYcrhi9TRiC
