### ISSUE TITLE
Npm not working for arts&culture [bug]

### ISSUE THREAD

**Issue by d762** [lovasoa/dezoomify#438]
The error occurs after the command: 

node dezoomify-node.js https://artsandculture.google.com/asset/the-night-watch-rembrandt-harmensz-van-rijn/eQEojRwTdypUKA rembrant.jpg

Output is:

Dezooming 'https://artsandculture.google.com/asset/the-night-watch-rembrandt-harmensz-van-rijn/eQEojRwTdypUKA' and saving it to 'rembrant.jpg'...
1% : Sent a request in order to get information about the image...
0% : Launched dezoomer...
Requested: https://artsandculture.google.com/asset/the-night-watch-rembrandt-harmensz-van-rijn/eQEojRwTdypUKA
Unable to find a proper dezoomer for:
https://artsandculture.google.com/asset/the-night-watch-rembrandt-harmensz-van-rijn/eQEojRwTdypUKA

(file:///home/icbosk/Desktop/dezoomify-master/dezoomers/automatic.js:30)
Error: Uncaught [Error: Unable to find a proper dezoomer for:
https://artsandculture.google.com/asset/the-night-watch-rembrandt-harmensz-van-rijn/eQEojRwTdypUKA]
    at reportException (/home/icbosk/Desktop/dezoomify-master/node-app/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:62:24)
    at innerInvokeEventListeners (/home/icbosk/Desktop/dezoomify-master/node-app/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:333:9)
    at invokeEventListeners (/home/icbosk/Desktop/dezoomify-master/node-app/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
    at XMLHttpRequestImpl._dispatch (/home/icbosk/Desktop/dezoomify-master/node-app/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
    at fireAnEvent (/home/icbosk/Desktop/dezoomify-master/node-app/node_modules/jsdom/lib/jsdom/living/helpers/events.js:18:36)
    at Request.properties.client.on (/home/icbosk/Desktop/dezoomify-master/node-app/node_modules/jsdom/lib/jsdom/living/xhr/XMLHttpRequest-impl.js:889:5)
    at Request.emit (events.js:203:15)
    at IncomingMessage.<anonymous> (/home/icbosk/Desktop/dezoomify-master/node-app/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15) Error: Unable to find a proper dezoomer for:
https://artsandculture.google.com/asset/the-night-watch-rembrandt-harmensz-van-rijn/eQEojRwTdypUKA
    at processNextUrl (file:///home/icbosk/Desktop/dezoomify-master/dezoomers/automatic.js:30:13)
    at file:///home/icbosk/Desktop/dezoomify-master/dezoomers/automatic.js:53:7
    at XMLHttpRequest.xhr.onload (file:///home/icbosk/Desktop/dezoomify-master/zoommanager.js:436:3)
    at XMLHttpRequest.idlUtils.tryImplForWrapper.addEventListener.event (/home/icbosk/Desktop/dezoomify-master/node-app/node_modules/jsdom/lib/jsdom/living/helpers/create-event-accessor.js:32:32)
    at innerInvokeEventListeners (/home/icbosk/Desktop/dezoomify-master/node-app/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:318:25)
    at invokeEventListeners (/home/icbosk/Desktop/dezoomify-master/node-app/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
    at XMLHttpRequestImpl._dispatch (/home/icbosk/Desktop/dezoomify-master/node-app/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
    at fireAnEvent (/home/icbosk/Desktop/dezoomify-master/node-app/node_modules/jsdom/lib/jsdom/living/helpers/events.js:18:36)
    at Request.properties.client.on (/home/icbosk/Desktop/dezoomify-master/node-app/node_modules/jsdom/lib/jsdom/living/xhr/XMLHttpRequest-impl.js:889:5)
    at Request.emit (events.js:203:15)

**Comment by lovasoa** [comment]
Hello!
  This is a duplicate of #306. 
  The easiest is to use dezoomify-rs.
