### ISSUE TITLE
"Error: Image given has not completed loading" when downloading

### ISSUE THREAD

**Issue by diversiforge** [lovasoa/dezoomify#69]
Platform: Linux x64
Node version: v5.12.0
Command: `node dezoomify-node.js "http://www.bl.uk/manuscripts/Viewer.aspx?ref=cotton_ms_nero_d_iv_fs001v" fs001v.jpg`

Output:

```
1% : Sent a request in order to get informations about the image...
Requested: http://www.bl.uk/manuscripts/Proxy.ashx?view=cotton_ms_nero_d_iv_fs001v.xml
0% : Preparing tiles load...
2% : Loading the tiles...
file:///dezoomify/zoommanager.js:62
        UI.ctx.drawImage(tileImg, x, y);
               ^

Error: Image given has not completed loading
    at Error (native)
    at Object.UI.drawTile (file:///dezoomify/zoommanager.js:62:9)
    at Request.tileLoaded [as _callback] (/dezoomify/node-app/dezoomify-node.js:51:10)
    at Request.self.callback (/dezoomify/node-app/node_modules/request/request.js:187:22)
    at emitTwo (events.js:100:13)
    at Request.emit (events.js:185:7)
    at Request.<anonymous> (/dezoomify/node-app/node_modules/request/request.js:1044:10)
    at emitOne (events.js:90:13)
    at Request.emit (events.js:182:7)
    at IncomingMessage.<anonymous> (/dezoomify/node-app/node_modules/request/request.js:965:12)
```

I've tried other pages, latest Node, and an `npm rebuild` without success. Thanks for your help :)

**Comment by LiloS** [comment]
Hi. Same issue. Maybe there are some workaround?

**Comment by giuppi** [comment]
Linux 4.4.0-138-generic #164-Ubuntu SMP Wed Oct 3 15:02:00 UTC 2018 i686 i686 i686 GNU/Linux
Node v8.14.0
`[...omissis...]
93% : Loading the tiles...
94% : Loading the tiles...
95% : Loading the tiles...
96% : Loading the tiles...
96% : Loading the tiles...
97% : Loading the tiles...
98% : Loading the tiles...
99% : Loading the tiles...
file:///opt/dezoomify/zoommanager.js:62
	UI.ctx.drawImage(tileImg, x, y);
	       ^

Error: Image given has not completed loading
    at Object.UI.drawTile (file:///opt/dezoomify/zoommanager.js:62:9)
    at Request.tileLoaded [as _callback] (/opt/dezoomify/node-app/dezoomify-node.js:51:10)
    at Request.self.callback (/opt/dezoomify/node-app/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/opt/dezoomify/node-app/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/opt/dezoomify/node-app/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
`

Downloading from nodejs gives this error. The same url works fine from dezoomify.html inside the browser.

**Comment by lovasoa** [comment]
I recently [updated](https://github.com/lovasoa/dezoomify/commit/56d9f69daa449c188d0a964f8d23deeec80a97fe) the node app. Hopefully, this should not happen anymore. Feel free to comment here or to open a new issue if you encounter new problems. Also, not that we now also distribute [dezoomify-rs](https://github.com/lovasoa/dezoomify-rs), which should be easier to setup and faster than the node app.
